### PR TITLE
Update AmazonSNS.php

### PR DESCRIPTION
**Pull request by rohit-wadhwa**
Adding support for sending message in JSON format. Its useful when we want to send a different message for each protocol. For example, using one publish action, you can send a short message to your SMS subscribers and a longer message to your email subscribers.

### CODE REVIEW

**Comment by chrisbarr** [comment]
Awesome, I didn't know about this parameter but seems extremely useful! Does it need to JSON encoded before being passed to the method? If it does, then maybe we should automatically `json_encode()` it and change the parameter to `array $messageStructure = null`.

**Comment by rohit-wadhwa** [comment]
We need to do the `json_encode()` before sending the message like below :
`<?php
require 'vendor/autoload.php';
define('AMAZON_ACCESS_KEY_ID', '<key>');
define('AMAZON_SECRET_ACCESS_KEY','<access_code>');
$AmazonSNS = new AmazonSNS(AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_ACCESS_KEY);
$AmazonSNS->setRegion('us-west-1');
try {

$topicArn = '<your Arn token>';

// Set the Topic's Display Name (required)
//$AmazonSNS->setTopicAttributes($topicArn, 'DisplayName', 'My SNS Topic Display Name');

$message = array("default"=>"This is the default Message, so no json goes here","APNS_SANDBOX"=> array("aps"=>array("alert"=>"You have got email.","badge" => 9,"sound" =>"default"),"email"=>array("orderID"=>"TEST001"), 
"sms"=> "Message body text here."));
$json_message=json_encode($message);
// And send a message to subscribers of this topic
$msg_id = $AmazonSNS->publish($topicArn,$json_message,'json');
// Success?
var_dump($msg_id);

}
catch(SNSException $e) {
    // Amazon SNS returned an error
    echo 'SNS returned the error "' . $e->getMessage() . '" and code ' . $e->getCode();
}
catch(APIException $e) {
    // Problem with the API
    echo 'There was an unknown problem with the API, returned code ' . $e->getCode();
}`

Not done json_encoding automatically.

**Comment by chrisbarr** [comment]
Ah I see, ok. Will merge now, thanks!

**Comment by rohit-wadhwa** [comment]
Your Welcome, you have done a wonderful code, its help a lot.

**Pull request merged**
