### PR TITLE
New API method: pushToEndpoint

### PR DESCRIPTION
**Pull request by vis4573**
New Method for pushing message to a device .(Fix for Issue #7)

### CODE REVIEW

**Comment by chrisbarr** [comment]
Thanks I'll take a look at this asap

**Comment by chrisbarr** [comment]
Changed the method name to `publishToEndpoint` just to make it a little more consistent with `publish`.
Thanks again for the PR!

**Comment by vis4573** [comment]
README not updated to 'publishToEndpoint'

**Comment by vis4573** [comment]
Its, updated now. :+1:

**Comment by chrisbarr** [comment]
Spotted, thanks 😄

**Pull request merged**
