### PR TITLE
Fixed an incorrect return type and removed restriction on optional parameter

### PR DESCRIPTION
**Pull request by chrisharrison**

### CODE REVIEW

**Comment by chrisbarr** [comment]
Thanks @chrisharrison, nice catch! Sorry to be picky but can you convert to tabs and remove the space in `if (` on line 455? Just to keep a consistent style.

**Comment by chrisharrison** [comment]
OK will do. I don't mind picky.

The formatting I was using is PSR-2. I'm a big advocate and encourage you
to adopt it.

**Comment by chrisharrison** [comment]
OK just pushed the formatting. Can you double check that is tabs I've committed?

**Comment by chrisbarr** [comment]
Thanks all looks good, merging now. I know, it's on my todo list...

**Pull request merged**
